"""empty message

Revision ID: 20e14d29b13a
Revises: f3a34f5be4fc
Create Date: 2023-01-26 14:43:09.758391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e14d29b13a'
down_revision = 'f3a34f5be4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agregar', sa.String(length=250), nullable=False),
    sa.Column('eliminar', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('poblacion', sa.String(length=250), nullable=True),
    sa.Column('bioma', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planetas')
    op.drop_table('favoritos')
    # ### end Alembic commands ###
