"""empty message

Revision ID: 4a29a2bc280d
Revises: bd18892cf97f
Create Date: 2023-01-26 15:17:11.296520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a29a2bc280d'
down_revision = 'bd18892cf97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehiculos_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'vehiculos', ['vehiculos_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehiculos_id')

    # ### end Alembic commands ###
