"""empty message

Revision ID: 60d93ac966fe
Revises: bfa4d08c981b
Create Date: 2023-01-26 19:33:07.500196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d93ac966fe'
down_revision = 'bfa4d08c981b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('personajes_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('vehiculos_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planetas_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('favoritos_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favoritos_usuario_id_fkey', 'user', ['usuario_id'], ['id'])
        batch_op.alter_column('planetas_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('vehiculos_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('personajes_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
