"""empty message

Revision ID: bbbc5879b93c
Revises: 5d2efcc177ac
Create Date: 2023-01-26 15:09:23.480991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbbc5879b93c'
down_revision = '5d2efcc177ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_column('agregar')
        batch_op.drop_column('eliminar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminar', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('agregar', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
