"""empty message

Revision ID: bfa4d08c981b
Revises: 4a29a2bc280d
Create Date: 2023-01-26 15:18:47.247935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa4d08c981b'
down_revision = '4a29a2bc280d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planetas_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'planetas', ['planetas_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planetas_id')

    # ### end Alembic commands ###
